apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: galegson-deployment
spec:
  selector:
    matchLabels:
      app: galegson-devops-project
  replicas: 3 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: galegson-devops-project
    spec:
      containers:
      - name: galegson-devops-project
        image: galegson/codepipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

